// Auto-generated by Supabase MCP (mcp__supabase__generate_typescript_types).
// 재생성: MCP 도구 또는 supabase CLI `supabase gen types typescript` 실행 후 이 파일 덮어쓰기.
// 수동 편집 금지.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[];

export type Database = {
  __InternalSupabase: {
    PostgrestVersion: '14.5';
  };
  public: {
    Tables: {
      companies: {
        Row: {
          business_summary: string | null;
          company_type: string | null;
          country: string;
          created_at: string;
          currency: string;
          customers: Json;
          data_source: string;
          group_name: string | null;
          homepage_url: string | null;
          id: string;
          is_seed: boolean;
          last_change_pct: number | null;
          last_price: number | null;
          last_updated_at: string | null;
          last_volume: number | null;
          market: string | null;
          market_cap: number | null;
          name: string;
          name_kr: string;
          products: Json;
          region: string | null;
          status: string;
          summary_updated_at: string | null;
          ticker: string | null;
          updated_at: string;
        };
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
      company_pages: {
        Row: { company_id: string; created_at: string; page: string };
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
      exchange_rates: {
        Row: { base: string; quote: string; rate: number; rate_date: string };
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
      exchange_rates_live: {
        Row: { base: string; quote: string; rate: number; updated_at: string };
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
      financials: {
        Row: {
          bps: number | null;
          cfps: number | null;
          cogs: number | null;
          company_id: string;
          currency: string;
          current_ratio: number | null;
          debt_ratio: number | null;
          dividend_yield: number | null;
          dps: number | null;
          ebitda: number | null;
          eps: number | null;
          ev_ebit: number | null;
          ev_ebitda: number | null;
          fiscal_quarter: number | null;
          fiscal_year: number;
          gross_margin: number | null;
          gross_profit: number | null;
          id: string;
          inventory: number | null;
          net_income: number | null;
          net_margin: number | null;
          operating_income: number | null;
          operating_margin: number | null;
          pbr: number | null;
          per: number | null;
          period_end_date: string | null;
          period_type: string;
          psr: number | null;
          revenue: number | null;
          roa: number | null;
          roe: number | null;
          sga: number | null;
          total_assets: number | null;
          total_equity: number | null;
          total_liabilities: number | null;
        };
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
      news: {
        Row: {
          company_id: string;
          created_at: string;
          id: string;
          published_at: string;
          source: string | null;
          summary: string | null;
          title: string;
          url: string;
        };
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
      oem_sales_group_country_month: {
        Row: { country: string; oem_group: string; sales: number; year_month: number };
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
      oem_sales_group_month: {
        Row: { oem_group: string; sales: number; year_month: number };
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
      oem_sales_group_pt_month: {
        Row: { oem_group: string; powertrain: string; sales: number; year_month: number };
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
      oem_sales_type_seg_month: {
        Row: { sales: number; segment: string; vehicle_type: string; year_month: number };
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
      stock_prices: {
        Row: {
          adj_close: number | null;
          close: number;
          company_id: string;
          high: number | null;
          low: number | null;
          open: number | null;
          trade_date: string;
          volume: number | null;
        };
        Insert: Record<string, never>;
        Update: Record<string, never>;
        Relationships: [];
      };
    };
    Views: {
      domestic_stocks_view: {
        Row: {
          business_summary: string | null;
          country: string | null;
          currency: string | null;
          customers: Json | null;
          financials_by_year: Json | null;
          fx_fin_to_krw: number | null;
          fx_to_krw: number | null;
          group_name: string | null;
          homepage_url: string | null;
          id: string | null;
          last_change_pct: number | null;
          last_price: number | null;
          last_updated_at: string | null;
          latest_quarter: Json | null;
          latest_revenue_krw: number | null;
          market: string | null;
          market_cap: number | null;
          name: string | null;
          name_kr: string | null;
          products: Json | null;
          sales_rank: number | null;
          status: string | null;
          summary_updated_at: string | null;
          ticker: string | null;
        };
        Relationships: [];
      };
      parts_top100_stocks_view: {
        Row: {
          business_summary: string | null;
          country: string | null;
          currency: string | null;
          customers: Json | null;
          financials_by_year: Json | null;
          fx_fin_to_krw: number | null;
          fx_to_krw: number | null;
          group_name: string | null;
          homepage_url: string | null;
          id: string | null;
          last_change_pct: number | null;
          last_price: number | null;
          last_updated_at: string | null;
          latest_quarter: Json | null;
          latest_revenue_krw: number | null;
          market: string | null;
          market_cap: number | null;
          name: string | null;
          name_kr: string | null;
          products: Json | null;
          sales_rank: number | null;
          status: string | null;
          summary_updated_at: string | null;
          ticker: string | null;
        };
        Relationships: [];
      };
      related_stocks_view: {
        Row: {
          business_summary: string | null;
          company_type: string | null;
          country: string | null;
          currency: string | null;
          customers: Json | null;
          financials_by_year: Json | null;
          fx_fin_to_krw: number | null;
          fx_to_krw: number | null;
          homepage_url: string | null;
          id: string | null;
          last_change_pct: number | null;
          last_price: number | null;
          last_updated_at: string | null;
          latest_quarter: Json | null;
          market: string | null;
          market_cap: number | null;
          name: string | null;
          name_kr: string | null;
          products: Json | null;
          region: string | null;
          status: string | null;
          summary_updated_at: string | null;
          ticker: string | null;
        };
        Relationships: [];
      };
    };
    Functions: {
      normalize_customer_name: { Args: { raw: string }; Returns: string };
    };
    Enums: Record<string, never>;
    CompositeTypes: Record<string, never>;
  };
};

/** 타입 헬퍼: View Row 빠른 추출 */
export type ViewRow<T extends keyof Database['public']['Views']> =
  Database['public']['Views'][T]['Row'];

/** 타입 헬퍼: Table Row 빠른 추출 */
export type TableRow<T extends keyof Database['public']['Tables']> =
  Database['public']['Tables'][T]['Row'];
