-- 비상장 자동차 부품사 42개 + OEM 2개 등록
-- 출처: data/auto_audit_candidates_2026-05-17.md (1~84위) WebSearch 전수 검증 (audit JSON)
-- 분류 결과: 부품사 42 / OEM 2 / 제외 39 / 보류 1(#21 현대철강)
--
-- 패턴 참고:
--   supabase/migrations/20260508000003_insert_korean_oem_unlisted.sql (비상장 OEM)
--   supabase/migrations/20260507000006_add_domestic_page_support.sql (domestic_stocks_view)
--   supabase/migrations/20260520000001_add_companies_dart_collection_status.sql
--
-- ticker: 한글 회사명(비상장 컨벤션). market=NULL, country='KR', currency='KRW', data_source='dart'.
-- dart_collection_status='pending' → 다음 분기 collect_dart_domestic.py 가 자동 수집.
-- DART corp_code 매핑은 scripts/lib/manual_dart_mapping.json 에 추가(이 파일과 별도 커밋).

-- ── Block 1: 비상장 자동차 부품사 INSERT ─────────────────────────────────
INSERT INTO companies (
  ticker, name, name_kr, market, country, currency, data_source, status,
  company_type, region, group_name, products, customers, homepage_url,
  dart_collection_status
) VALUES
  ('신양금속공업', 'SHINYANG METAL IND. CO.,LTD', '신양금속공업', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"알루미늄 압출"},{"name":"ABS"},{"name":"범퍼"},{"name":"루프랙"}]'::jsonb,
   '[{"name":"현대차"},{"name":"기아"}]'::jsonb,
   'https://www.shin-yang.com', 'pending'),
  ('계양정밀', 'KEY YANG PRECISION CO., LTD.', '계양정밀', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"터보차저 WGT"},{"name":"터보차저 VGT"}]'::jsonb,
   '[{"name":"GM"}]'::jsonb,
   'http://www.keyyang.co.kr', 'pending'),
  ('메탈다인코리아', 'Metaldyne Korea Ltd.', '메탈다인코리아', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', 'American Axle',
   '[{"name":"자동차 엔진 부품"},{"name":"파워트레인 부품"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending'),
  ('커민스필터', 'Cummins Filtration Co.Ltd', '커민스필터', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', 'Cummins',
   '[{"name":"필터"},{"name":"터보차저"},{"name":"후처리"},{"name":"연료시스템"}]'::jsonb,
   '[{"name":"현대차"},{"name":"타타대우"},{"name":"두산인프라코어"},{"name":"현대건설기계"},{"name":"볼보"},{"name":"DAF"}]'::jsonb,
   NULL, 'pending'),
  ('동산공업', 'DongSan Inc.', '동산공업', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 부품"}]'::jsonb,
   '[]'::jsonb,
   'http://dongsanind.co.kr', 'pending'),
  ('일신캐스팅', 'IL SHIN Casting Co., Ltd.', '일신캐스팅', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 다이캐스팅 부품"},{"name":"알루미늄 주조"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending'),
  ('한국캐스팅', 'HAN KOOK CASTING CORP.', '한국캐스팅', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"변속기 케이스"},{"name":"알루미늄 주조 부품"}]'::jsonb,
   '[]'::jsonb,
   'http://www.diecastingkorea.com', 'pending'),
  ('동일기계공업', 'DONG IL MACHINERY CO., LTD.', '동일기계공업', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"에어컨 컴프레서 밸브"}]'::jsonb,
   '[]'::jsonb,
   'http://dongilm.com', 'pending'),
  ('코아오토모티브', 'KOA AUTOMOTIV', '코아오토모티브', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"모터코어"},{"name":"ABS 모터"},{"name":"EVP/EOP 펌프모터"},{"name":"BLDC 모터"}]'::jsonb,
   '[]'::jsonb,
   'http://koaautomotive.com', 'pending'),
  ('의신정밀', 'Uey shin Precision.co', '의신정밀', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 부품 정밀가공"},{"name":"프레스 툴"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending'),
  ('대진정밀', 'DAE JIN PRECISION INDUSTRIAL CO.,LTD.', '대진정밀', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 부품"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending'),
  ('한국메탈', 'HANKUK METAL CO., LTD.', '한국메탈', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 단조 부품"}]'::jsonb,
   '[]'::jsonb,
   'http://hankookmetal.com', 'pending'),
  ('태창공업', 'TAE CHANG INDUSTRIAL CO.LTD', '태창공업', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"엔진 부품"},{"name":"섀시 부품"}]'::jsonb,
   '[]'::jsonb,
   'http://www.taechang-ec.co.kr', 'pending'),
  ('금오중공업', 'KUMOH HEAVY INDUSTRIES CO., LTD', '금오중공업', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 램프 부품"},{"name":"다이캐스팅"}]'::jsonb,
   '[]'::jsonb,
   'http://kumohheavy.com', 'pending'),
  ('대한메탈', 'Dae Han Metal', '대한메탈', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"조향장치 냉간단조 부품"}]'::jsonb,
   '[{"name":"현대차"},{"name":"기아"}]'::jsonb,
   NULL, 'pending'),
  ('성신파츠', 'SSPARTS. CO. LTD', '성신파츠', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 부품"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending'),
  ('세화자동차', 'SEHWA MOTORS', '세화자동차', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"특장차"},{"name":"특장차 부품"}]'::jsonb,
   '[]'::jsonb,
   'http://esmotors.co.kr', 'pending'),
  ('황성공업', 'HWANG SUNG IND. CO., LTD.', '황성공업', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 차체 부품"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending'),
  ('오토글로벌', 'AUTO GLOBAL CO. ,LTD', '오토글로벌', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 차체 부품"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending'),
  ('유진기공', 'Yujin Machinery Co., Ltd.', '유진기공', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"브레이크 시스템"},{"name":"브레이크 컨트롤"},{"name":"공급장치"}]'::jsonb,
   '[]'::jsonb,
   'http://www.yujinltd.co.kr', 'pending'),
  ('다이나믹오토', 'Dynamic Auto', '다이나믹오토', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 부품"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending'),
  ('동우특장차', 'DONGWOO MOTOR CO.,LTD', '동우특장차', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"평판트레일러"},{"name":"저상트레일러"},{"name":"카 캐리어"}]'::jsonb,
   '[]'::jsonb,
   'http://www.dongwoomotor.com', 'pending'),
  ('세일정밀', 'Seil precision co, ltd', '세일정밀', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"실린더 블록"},{"name":"실린더 헤드"},{"name":"크랭크샤프트"},{"name":"캠샤프트"},{"name":"변속기 케이스"}]'::jsonb,
   '[]'::jsonb,
   'http://www.seilpt.com', 'pending'),
  ('비엠씨', 'Best Mobility Core Technology CO.,LTD', '비엠씨', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"구동모터 코어"},{"name":"스테이터 코어"},{"name":"로터 코어"}]'::jsonb,
   '[{"name":"현대차"},{"name":"기아"}]'::jsonb,
   'http://www.bmcmobility.com', 'pending'),
  ('일진금속공업', 'IL JIN metal. Inc', '일진금속공업', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', 'ILJIN',
   '[{"name":"CV 조인트"},{"name":"냉간단조 부품"}]'::jsonb,
   '[]'::jsonb,
   'http://iljinmi.co.kr', 'pending'),
  ('대성정공', 'DAESEONG PRECISION CO., LTD.', '대성정공', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"차체 부품"},{"name":"경량화 부품"}]'::jsonb,
   '[{"name":"현대차"}]'::jsonb,
   'http://dstrust.co.kr', 'pending'),
  ('신성전자정밀', 'Shin Sung Electronic Precision co. ltd', '신성전자정밀', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 전장 Sub assembly"}]'::jsonb,
   '[]'::jsonb,
   'http://ssep.co.kr', 'pending'),
  ('카네비모빌리티', 'CARNAVICOM', '카네비모빌리티', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"LiDAR 센서"},{"name":"차량용 내비게이션"},{"name":"V2X 통신"},{"name":"DCU"}]'::jsonb,
   '[]'::jsonb,
   'http://carnavi.com', 'pending'),
  ('화영오토텍', 'HWAYOUNG AUTOTEC,LTD.', '화영오토텍', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"휠허브 베어링"},{"name":"알터네이터"},{"name":"스타터 모터"},{"name":"트랜스미션"},{"name":"라디에이터 팬"}]'::jsonb,
   '[{"name":"현대차"}]'::jsonb,
   'https://hyautotec.co.kr', 'pending'),
  ('엘에스이모빌리티솔루션', 'LS e-Mobility Solutions Co., Ltd.', '엘에스이모빌리티솔루션', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', 'LS',
   '[{"name":"EV Relay"},{"name":"BDU"},{"name":"고전압 보호장치"}]'::jsonb,
   '[{"name":"현대차"},{"name":"기아"},{"name":"GM"},{"name":"르노"},{"name":"벤츠"},{"name":"VW"},{"name":"볼보"},{"name":"포르쉐"}]'::jsonb,
   'https://www.lsems.com', 'pending'),
  ('제이디오토모티브', 'JD Automotive Corp', '제이디오토모티브', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"브레이크 캘리퍼"},{"name":"프론트 하우징"},{"name":"MOC 리어 하우징"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending'),
  ('신라공업', 'SHILLA INDUSTRIAL CO.,LTD.', '신라공업', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 부품"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending'),
  ('대양전장', 'DAEYANG ELECTRIC SUPPLY CO., LTD.', '대양전장', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 전기 하네스"}]'::jsonb,
   '[]'::jsonb,
   'http://dsc.daeyang.co.kr', 'pending'),
  ('르네사스일렉트로닉스한국', 'Renesas Electronics Korea Co.,Ltd', '르네사스일렉트로닉스한국', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', 'Renesas',
   '[{"name":"자동차 MCU(RH850)"},{"name":"자동차 SoC"},{"name":"차량용 반도체"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending'),
  ('모베이스오토테크', 'MOBASE AUTO TECH CO.,LTD', '모베이스오토테크', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', '모베이스',
   '[{"name":"스마트키 시스템"},{"name":"ECU"},{"name":"차량용 스위치"}]'::jsonb,
   '[{"name":"현대차"},{"name":"기아"}]'::jsonb,
   NULL, 'pending'),
  ('케이피엑스헌츠만폴리우레탄오토모티브', 'KPX HUNTSMAN POLYURETHANES AUTOMOTIVE Co., Ltd.', '케이피엑스헌츠만폴리우레탄오토모티브', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', 'KPX/Huntsman',
   '[{"name":"자동차 시트 폴리우레탄"},{"name":"후드 라이너 폼"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending'),
  ('엘에스오토모티브테크놀로지스', 'LS Automotive Technologies Co., Ltd.', '엘에스오토모티브테크놀로지스', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', 'LS',
   '[{"name":"스위치 모듈"},{"name":"차량용 릴레이"},{"name":"센서"},{"name":"E-모듈"},{"name":"인테리어 램프"}]'::jsonb,
   '[{"name":"현대차"},{"name":"기아"},{"name":"쌍용차"},{"name":"GM"},{"name":"닛산"},{"name":"다임러"},{"name":"아우디"}]'::jsonb,
   'https://lsautomotive.com', 'pending'),
  ('엘티정밀', 'LT PRECISION CO., LTD', '엘티정밀', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', 'LT',
   '[{"name":"AL 단조 부품"},{"name":"자동차 솔레노이드 밸브"},{"name":"EV 배터리 쿨링핀"},{"name":"AC 컴프레서 부품"}]'::jsonb,
   '[]'::jsonb,
   'http://ltpr.co.kr', 'pending'),
  ('엠에스오토시스', 'MSAUTOSYS.CO.,LTD', '엠에스오토시스', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', '엠에스오토텍',
   '[{"name":"차체 프레임"},{"name":"핫스탬핑 부품"},{"name":"BIW"}]'::jsonb,
   '[{"name":"현대차"},{"name":"기아"}]'::jsonb,
   'https://msautosys.ms-global.com', 'pending'),
  ('세일전장', 'SEIL ELECTRIC DRIVES CORPORATION', '세일전장', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"자동차 전장 부품"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending'),
  ('포레시아코리아시트', 'FAS Yeongcheon Co.,Ltd.', '포레시아코리아시트', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', 'FORVIA/Faurecia',
   '[{"name":"자동차 시트"}]'::jsonb,
   '[{"name":"현대차"},{"name":"기아"},{"name":"르노"},{"name":"닛산"}]'::jsonb,
   NULL, 'pending'),
  ('세진메탈', 'SEJIN METAL CO.,LTD', '세진메탈', NULL, 'KR', 'KRW', 'dart', 'active',
   '부품사', '한국', NULL,
   '[{"name":"다이캐스팅용 알루미늄 합금"},{"name":"제강용 탈산제"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending')
ON CONFLICT (ticker) DO NOTHING;

-- ── Block 2: 비상장 OEM INSERT (우즈오토코리아, 타타대우모빌리티) ───────
INSERT INTO companies (
  ticker, name, name_kr, market, country, currency, data_source, status,
  company_type, region, group_name, products, customers, homepage_url,
  dart_collection_status
) VALUES
  ('우즈오토코리아', 'Uzauto Korea', '우즈오토코리아', NULL, 'KR', 'KRW', 'dart', 'active',
   'OEM', '한국', NULL,
   '[{"name":"UzAuto 차량 부품 한국 공급"}]'::jsonb,
   '[]'::jsonb,
   'http://www.uzautokorea.com', 'pending'),
  ('타타대우모빌리티', 'Tata Daewoo Mobility Co., Ltd.', '타타대우모빌리티', NULL, 'KR', 'KRW', 'dart', 'active',
   'OEM', '한국', '타타',
   '[{"name":"맥센(Maxen)"},{"name":"프리마"},{"name":"기쎈(전기트럭)"}]'::jsonb,
   '[]'::jsonb,
   NULL, 'pending')
ON CONFLICT (ticker) DO NOTHING;

-- ── Block 3: company_pages 매핑 ─────────────────────────────────────────
-- 부품사 42 → /domestic
INSERT INTO company_pages (company_id, page)
SELECT id, 'domestic' FROM companies
WHERE ticker IN (
  '신양금속공업', '계양정밀', '메탈다인코리아', '커민스필터', '동산공업',
  '일신캐스팅', '한국캐스팅', '동일기계공업', '코아오토모티브', '의신정밀',
  '대진정밀', '한국메탈', '태창공업', '금오중공업', '대한메탈',
  '성신파츠', '세화자동차', '황성공업', '오토글로벌', '유진기공',
  '다이나믹오토', '동우특장차', '세일정밀', '비엠씨', '일진금속공업',
  '대성정공', '신성전자정밀', '카네비모빌리티', '화영오토텍', '엘에스이모빌리티솔루션',
  '제이디오토모티브', '신라공업', '대양전장', '르네사스일렉트로닉스한국', '모베이스오토테크',
  '케이피엑스헌츠만폴리우레탄오토모티브', '엘에스오토모티브테크놀로지스', '엘티정밀',
  '엠에스오토시스', '세일전장', '포레시아코리아시트', '세진메탈'
)
ON CONFLICT (company_id, page) DO NOTHING;

-- OEM 2 → /related-stocks
INSERT INTO company_pages (company_id, page)
SELECT id, 'related-stocks' FROM companies
WHERE ticker IN ('우즈오토코리아', '타타대우모빌리티')
ON CONFLICT (company_id, page) DO NOTHING;
