-- 휴머노이드 기업 시드 67사.
--
-- 출처: 6묶음 병렬 조사(research-pplx) → 묶음별 교차검증 → 티커 기계검증
--   · 해외 상장 29건: yfinance 실조회로 이름·통화 대조 전건 통과
--   · 국내 상장 11건: DART 공식 기업목록(corpCode)과 정식명칭 전건 일치
--   · 비상장 27건: 티커 없음. 기업가치는 확인된 곳만 채우고 나머지는 NULL(추측 금지)
--
-- 구성
--   [1] 시드 이전부터 있던 겸업사 13곳 — 로봇 역할·제품만 덧붙인다(자동차 페이지 매핑은 유지)
--   [2] 그 13곳의 humanoid 페이지 매핑 (AFTER INSERT 트리거는 UPDATE 에 발동하지 않는다)
--   [3] 신규 54곳 — 트리거가 robot_roles 를 보고 humanoid 페이지에 자동 매핑
--
-- 멱등: 두 번 실행해도 회사 수·매핑 수·제품 수가 변하지 않는 것을 실측 확인했다
--       (products 는 카테고리 존재 검사로 덧붙임을 건너뛴다 — 20260824000005 의 왕복 수리가 전제).
-- UUID 하드코딩 없음 — ticker/name_kr 자연키로만 대상을 찾는다.

-- 휴머노이드 기업 시드 — 조사(6묶음 병렬) + 교차검증 + 티커 기계검증(yfinance·DART) 결과
-- 총 67사 · 신규 INSERT 54 · 기존 UPDATE 35

-- [1] 기존 회사: 로봇 역할 태그만 추가 (자동차 페이지 매핑은 그대로 유지)
UPDATE companies SET robot_roles = ARRAY['parts']::text[] WHERE ticker = '6594.T';  -- 니덱
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "모터", "category": "모터"}]'::jsonb WHERE ticker = '6594.T' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"모터"}]'::jsonb);
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "감속기", "category": "감속기"}]'::jsonb WHERE ticker = '6594.T' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"감속기"}]'::jsonb);
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "액추에이터", "category": "액추에이터"}]'::jsonb WHERE ticker = '6594.T' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"액추에이터"}]'::jsonb);
UPDATE companies SET robot_roles = ARRAY['parts']::text[] WHERE ticker = '601689.SS';  -- 닝보투오푸
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "액추에이터", "category": "액추에이터"}]'::jsonb WHERE ticker = '601689.SS' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"액추에이터"}]'::jsonb);
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "볼스크류/리니어", "category": "볼스크류/리니어"}]'::jsonb WHERE ticker = '601689.SS' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"볼스크류/리니어"}]'::jsonb);
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "구조기구", "category": "구조기구"}]'::jsonb WHERE ticker = '601689.SS' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"구조기구"}]'::jsonb);
UPDATE companies SET robot_roles = ARRAY['parts']::text[] WHERE ticker = '6723.T';  -- 르네사스
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "위치센서", "category": "위치센서"}]'::jsonb WHERE ticker = '6723.T' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"위치센서"}]'::jsonb);
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "제어AI칩", "category": "제어AI칩"}]'::jsonb WHERE ticker = '6723.T' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"제어AI칩"}]'::jsonb);
UPDATE companies SET robot_roles = ARRAY['parts']::text[] WHERE ticker = '012860';  -- 모베이스전자
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "로봇 그리퍼", "category": "그리퍼핸드"}]'::jsonb WHERE ticker = '012860' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"그리퍼핸드"}]'::jsonb);
UPDATE companies SET robot_roles = ARRAY['parts']::text[] WHERE ticker = 'SHA0.DE';  -- 셰플러
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "로봇 리니어 액추에이터(Ewellix)", "category": "볼스크류/리니어"}]'::jsonb WHERE ticker = 'SHA0.DE' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"볼스크류/리니어"}]'::jsonb);
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "로봇 관절 베어링·액추에이터", "category": "액추에이터"}]'::jsonb WHERE ticker = 'SHA0.DE' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"액추에이터"}]'::jsonb);
UPDATE companies SET robot_roles = ARRAY['parts']::text[] WHERE ticker = '204320';  -- 에이치엘만도
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "로봇 액추에이터", "category": "액추에이터"}]'::jsonb WHERE ticker = '204320' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"액추에이터"}]'::jsonb);
UPDATE companies SET robot_roles = ARRAY['parts']::text[] WHERE ticker = '105550';  -- 엣지파운드리
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "인덕티브 위치센서", "category": "위치센서"}]'::jsonb WHERE ticker = '105550' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"위치센서"}]'::jsonb);
UPDATE companies SET robot_roles = ARRAY['parts']::text[] WHERE ticker = 'ON';  -- 온세미
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "비전카메라", "category": "비전카메라"}]'::jsonb WHERE ticker = 'ON' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"비전카메라"}]'::jsonb);
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "제어AI칩", "category": "제어AI칩"}]'::jsonb WHERE ticker = 'ON' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"제어AI칩"}]'::jsonb);
UPDATE companies SET robot_roles = ARRAY['parts']::text[] WHERE ticker = 'IFX.DE';  -- 인피니온
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "위치센서", "category": "위치센서"}]'::jsonb WHERE ticker = 'IFX.DE' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"위치센서"}]'::jsonb);
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "제어AI칩", "category": "제어AI칩"}]'::jsonb WHERE ticker = 'IFX.DE' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"제어AI칩"}]'::jsonb);
UPDATE companies SET robot_roles = ARRAY['parts']::text[] WHERE ticker = 'TXN';  -- 텍사스인스트루먼트
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "제어AI칩", "category": "제어AI칩"}]'::jsonb WHERE ticker = 'TXN' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"제어AI칩"}]'::jsonb);
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "위치센서", "category": "위치센서"}]'::jsonb WHERE ticker = 'TXN' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"위치센서"}]'::jsonb);
UPDATE companies SET robot_roles = ARRAY['parts']::text[] WHERE ticker = '퓨트로닉';  -- 퓨트로닉
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "정밀 액추에이터(모터·센서·감속기·제어기 수직통합)", "category": "액추에이터"}]'::jsonb WHERE ticker = '퓨트로닉' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"액추에이터"}]'::jsonb);
UPDATE companies SET robot_roles = ARRAY['parts']::text[] WHERE ticker = '012330';  -- 현대모비스
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "로봇 바디 액추에이터(E-아틀라스 31종 개발)", "category": "액추에이터"}]'::jsonb WHERE ticker = '012330' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"액추에이터"}]'::jsonb);
UPDATE companies SET robot_roles = ARRAY['humanoid']::text[] WHERE ticker = '005380';  -- 현대차
UPDATE companies SET products = coalesce(products,'[]'::jsonb) || '[{"name": "휴머노이드 로봇(아틀라스·보스턴다이내믹스)", "category": "기타"}]'::jsonb WHERE ticker = '005380' AND NOT (coalesce(products,'[]'::jsonb) @> '[{"category":"기타"}]'::jsonb);

-- [2] 기존 회사: 휴머노이드 페이지 매핑 추가
--     (AFTER INSERT 트리거는 UPDATE 에 발동하지 않으므로 수동으로 넣는다)
INSERT INTO company_pages (company_id, page) SELECT id, 'humanoid' FROM companies WHERE ticker = '6594.T' ON CONFLICT (company_id, page) DO NOTHING;  -- 니덱
INSERT INTO company_pages (company_id, page) SELECT id, 'humanoid' FROM companies WHERE ticker = '601689.SS' ON CONFLICT (company_id, page) DO NOTHING;  -- 닝보투오푸
INSERT INTO company_pages (company_id, page) SELECT id, 'humanoid' FROM companies WHERE ticker = '6723.T' ON CONFLICT (company_id, page) DO NOTHING;  -- 르네사스
INSERT INTO company_pages (company_id, page) SELECT id, 'humanoid' FROM companies WHERE ticker = '012860' ON CONFLICT (company_id, page) DO NOTHING;  -- 모베이스전자
INSERT INTO company_pages (company_id, page) SELECT id, 'humanoid' FROM companies WHERE ticker = 'SHA0.DE' ON CONFLICT (company_id, page) DO NOTHING;  -- 셰플러
INSERT INTO company_pages (company_id, page) SELECT id, 'humanoid' FROM companies WHERE ticker = '204320' ON CONFLICT (company_id, page) DO NOTHING;  -- 에이치엘만도
INSERT INTO company_pages (company_id, page) SELECT id, 'humanoid' FROM companies WHERE ticker = '105550' ON CONFLICT (company_id, page) DO NOTHING;  -- 엣지파운드리
INSERT INTO company_pages (company_id, page) SELECT id, 'humanoid' FROM companies WHERE ticker = 'ON' ON CONFLICT (company_id, page) DO NOTHING;  -- 온세미
INSERT INTO company_pages (company_id, page) SELECT id, 'humanoid' FROM companies WHERE ticker = 'IFX.DE' ON CONFLICT (company_id, page) DO NOTHING;  -- 인피니온
INSERT INTO company_pages (company_id, page) SELECT id, 'humanoid' FROM companies WHERE ticker = 'TXN' ON CONFLICT (company_id, page) DO NOTHING;  -- 텍사스인스트루먼트
INSERT INTO company_pages (company_id, page) SELECT id, 'humanoid' FROM companies WHERE ticker = '퓨트로닉' ON CONFLICT (company_id, page) DO NOTHING;  -- 퓨트로닉
INSERT INTO company_pages (company_id, page) SELECT id, 'humanoid' FROM companies WHERE ticker = '012330' ON CONFLICT (company_id, page) DO NOTHING;  -- 현대모비스
INSERT INTO company_pages (company_id, page) SELECT id, 'humanoid' FROM companies WHERE ticker = '005380' ON CONFLICT (company_id, page) DO NOTHING;  -- 현대차

-- [3] 신규 회사 (트리거가 robot_roles 를 보고 humanoid 페이지에 자동 매핑)
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, '1X Technologies AS', '1X 테크놀로지스', NULL, 'US', 'USD', 'web_search', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}]'::jsonb, ARRAY['humanoid']::text[], NULL, 136500000, NULL, 'https://www.1x.tech' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '1X 테크놀로지스');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'HD Hyundai Robotics Co., Ltd.', 'HD현대로보틱스', NULL, 'KR', 'KRW', 'dart', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}]'::jsonb, ARRAY['humanoid']::text[], 1298700000, 129870000, '2025-10-24', 'https://www.hd-hyundairobotics.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = 'HD현대로보틱스');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'RLS Merilna tehnika d.o.o.', 'RLS', NULL, 'SI', 'EUR', 'web_search', 'active', '부품사', '[{"name": "위치센서", "category": "위치센서"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.rls.si' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = 'RLS');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '6268.T', 'Nabtesco Corporation', '나브테스코', 'TSE', 'JP', 'JPY', 'yfinance', 'active', '부품사', '[{"name": "감속기", "category": "감속기"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.nabtesco.com/en/' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '6268.T');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT 'NOVT', 'Novanta Inc.', '노반타', 'NASDAQ', 'US', 'USD', 'yfinance', 'active', '부품사', '[{"name": "위치센서", "category": "위치센서"}, {"name": "모터", "category": "모터"}, {"name": "그리퍼핸드", "category": "그리퍼핸드"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.novanta.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = 'NOVT');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'NEURA Robotics GmbH', '뉴라 로보틱스', NULL, 'DE', 'EUR', 'web_search', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}]'::jsonb, ARRAY['humanoid']::text[], NULL, NULL, NULL, 'https://neura-robotics.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '뉴라 로보틱스');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '348340', 'Neuromeka Co., Ltd.', '뉴로메카', 'KOSDAQ', 'KR', 'KRW', 'fnguide', 'active', '부품사', '[{"name": "액추에이터", "category": "액추에이터"}, {"name": "감속기", "category": "감속기"}, {"name": "모터", "category": "모터"}]'::jsonb, ARRAY['humanoid','parts']::text[], NULL, NULL, NULL, 'https://www.neuromeka.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '348340');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '454910', 'Doosan Robotics Inc.', '두산로보틱스', 'KOSPI', 'KR', 'KRW', 'fnguide', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}]'::jsonb, ARRAY['humanoid']::text[], NULL, NULL, NULL, 'https://www.doosanrobotics.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '454910');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '277810', 'Rainbow Robotics Co., Ltd.', '레인보우로보틱스', 'KOSDAQ', 'KR', 'KRW', 'fnguide', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}, {"name": "액추에이터", "category": "액추에이터"}]'::jsonb, ARRAY['humanoid']::text[], NULL, NULL, NULL, 'https://www.rainbow-robotics.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '277810');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '090360', 'Robostar Co., Ltd.', '로보스타', 'KOSDAQ', 'KR', 'KRW', 'fnguide', 'active', '부품사', '[{"name": "기타", "category": "기타"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.robostar.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '090360');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '108490', 'ROBOTIS Co., Ltd.', '로보티즈', 'KOSDAQ', 'KR', 'KRW', 'fnguide', 'active', '부품사', '[{"name": "액추에이터", "category": "액추에이터"}, {"name": "감속기", "category": "감속기"}, {"name": "그리퍼핸드", "category": "그리퍼핸드"}]'::jsonb, ARRAY['humanoid','parts']::text[], NULL, NULL, NULL, 'http://www.robotis.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '108490');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'ROBROS', '로브로스', NULL, 'KR', 'KRW', 'dart', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}]'::jsonb, ARRAY['humanoid']::text[], 57720000, 11255000, '2026-04-30', 'https://www.robros.co.kr' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '로브로스');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'Rollvis SA', '롤비스', NULL, 'CH', 'CHF', 'web_search', 'active', '부품사', '[{"name": "볼스크류/리니어", "category": "볼스크류/리니어"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://rollvis.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '롤비스');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '688017.SS', 'Leader Harmonious Drive Systems Co., Ltd. (Leaderdrive)', '뤼디셰보(녹적해파)', 'SSE STAR', 'CN', 'CNY', 'yfinance', 'active', '부품사', '[{"name": "감속기", "category": "감속기"}, {"name": "볼스크류/리니어", "category": "볼스크류/리니어"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'http://www.leaderdrive.cn' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '688017.SS');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT 'MCHP', 'Microchip Technology Incorporated', '마이크로칩 테크놀로지', 'NASDAQ', 'US', 'USD', 'yfinance', 'active', '부품사', '[{"name": "제어AI칩", "category": "제어AI칩"}, {"name": "위치센서", "category": "위치센서"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.microchip.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = 'MCHP');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'maxon international ag', '맥슨', NULL, 'CH', 'CHF', 'web_search', 'active', '부품사', '[{"name": "모터", "category": "모터"}, {"name": "감속기", "category": "감속기"}, {"name": "위치센서", "category": "위치센서"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.maxongroup.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '맥슨');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT 'MELE.BR', 'Melexis NV', '멜렉시스', 'BRU', 'BE', 'EUR', 'yfinance', 'active', '부품사', '[{"name": "위치센서", "category": "위치센서"}, {"name": "제어AI칩", "category": "제어AI칩"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.melexis.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = 'MELE.BR');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '6479.T', 'MinebeaMitsumi Inc.', '미네베아미쓰미', 'TSE', 'JP', 'JPY', 'yfinance', 'active', '부품사', '[{"name": "모터", "category": "모터"}, {"name": "기타", "category": "기타"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.minebeamitsumi.com/english/' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '6479.T');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'Boston Dynamics, Inc.', '보스턴다이내믹스', NULL, 'US', 'USD', 'web_search', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}]'::jsonb, ARRAY['humanoid']::text[], NULL, NULL, NULL, 'https://bostondynamics.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '보스턴다이내믹스');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '004380', 'SAMICK THK CO., LTD.', '삼익THK', 'KOSPI', 'KR', 'KRW', 'fnguide', 'active', '부품사', '[{"name": "볼스크류/리니어", "category": "볼스크류/리니어"}, {"name": "액추에이터", "category": "액추에이터"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.samickthk.co.kr' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '004380');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '603009.SS', 'Shanghai Beite Technology Group Co., Ltd.', '상하이 베이터커지그룹(북특과기)', 'SSE', 'CN', 'CNY', 'yfinance', 'active', '부품사', '[{"name": "볼스크류/리니어", "category": "볼스크류/리니어"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'http://www.sh-beite.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '603009.SS');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'Sanctuary Cognitive Systems Corporation', '생추어리 AI', NULL, 'CA', 'CAD', 'web_search', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}, {"name": "그리퍼핸드", "category": "그리퍼핸드"}]'::jsonb, ARRAY['humanoid']::text[], NULL, NULL, NULL, 'https://sanctuary.ai' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '생추어리 AI');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '003021.SZ', 'Shenzhen Zhaowei Machinery & Electronics Co., Ltd.', '선전 자오웨이지뎬(조위기전)', 'SZSE', 'CN', 'CNY', 'yfinance', 'active', '부품사', '[{"name": "그리퍼핸드", "category": "그리퍼핸드"}, {"name": "모터", "category": "모터"}, {"name": "감속기", "category": "감속기"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.zwgearbox.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '003021.SZ');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '6302.T', 'Sumitomo Heavy Industries, Ltd.', '스미토모중기계공업', 'TSE', 'JP', 'JPY', 'yfinance', 'active', '부품사', '[{"name": "감속기", "category": "감속기"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.shi.co.jp/english/' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '6302.T');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT 'ALGM', 'Allegro MicroSystems, Inc.', '알레그로 마이크로시스템즈', 'NASDAQ', 'US', 'USD', 'yfinance', 'active', '부품사', '[{"name": "위치센서", "category": "위치센서"}, {"name": "제어AI칩", "category": "제어AI칩"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.allegromicro.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = 'ALGM');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '140670', 'RS Automation Co., Ltd.', '알에스오토메이션', 'KOSDAQ', 'KR', 'KRW', 'fnguide', 'active', '부품사', '[{"name": "위치센서", "category": "위치센서"}, {"name": "기타", "category": "기타"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'http://www.rsautomation.co.kr' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '140670');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'Agility Robotics, Inc.', '애질리티 로보틱스', NULL, 'US', 'USD', 'web_search', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}]'::jsonb, ARRAY['humanoid']::text[], 2500000000, 641250000, '2026-06-24', 'https://www.agilityrobotics.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '애질리티 로보틱스');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'Apptronik, Inc.', '앱트로닉', NULL, 'US', 'USD', 'web_search', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}]'::jsonb, ARRAY['humanoid']::text[], 5500000000, 963000000, '2026-02-11', 'https://apptronik.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '앱트로닉');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '6506.T', 'YASKAWA Electric Corporation', '야스카와전기', 'TSE', 'JP', 'JPY', 'yfinance', 'active', '부품사', '[{"name": "모터", "category": "모터"}, {"name": "액추에이터", "category": "액추에이터"}]'::jsonb, ARRAY['humanoid','parts']::text[], NULL, NULL, NULL, 'https://www.yaskawa-global.com/' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '6506.T');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '389500', 'SBB Tech Co., Ltd.', '에스비비테크', 'KOSDAQ', 'KR', 'KRW', 'fnguide', 'active', '부품사', '[{"name": "감속기", "category": "감속기"}, {"name": "액추에이터", "category": "액추에이터"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'http://www.sbb.co.kr' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '389500');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '002747.SZ', 'Estun Automation Co., Ltd.', '에스툰 오토메이션', 'SZSE', 'CN', 'CNY', 'yfinance', 'active', '부품사', '[{"name": "모터", "category": "모터"}, {"name": "액추에이터", "category": "액추에이터"}]'::jsonb, ARRAY['humanoid','parts']::text[], NULL, NULL, NULL, 'https://www.estun.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '002747.SZ');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '058610', 'SPG Co., Ltd.', '에스피지', 'KOSDAQ', 'KR', 'KRW', 'fnguide', 'active', '부품사', '[{"name": "감속기", "category": "감속기"}, {"name": "모터", "category": "모터"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.spg.co.kr' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '058610');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'Aidin Robotics', '에이딘로보틱스', NULL, 'KR', 'KRW', 'dart', 'active', '부품사', '[{"name": "힘토크센서", "category": "힘토크센서"}]'::jsonb, ARRAY['parts']::text[], NULL, 14430000, '2024-09-23', 'https://www.aidinrobotics.co.kr' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '에이딘로보틱스');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'AeiROBOT Co., Ltd.', '에이로봇', NULL, 'KR', 'KRW', 'dart', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}, {"name": "액추에이터", "category": "액추에이터"}]'::jsonb, ARRAY['humanoid']::text[], NULL, 9740000, '2025-07-11', 'http://www.arobot4all.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '에이로봇');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT 'AMS.SW', 'ams-OSRAM AG', '에이엠에스 오스람', 'SIX', 'AT', 'EUR', 'yfinance', 'active', '부품사', '[{"name": "위치센서", "category": "위치센서"}, {"name": "비전카메라", "category": "비전카메라"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://ams-osram.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = 'AMS.SW');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'NRT', '엔알티', NULL, 'KR', 'KRW', 'dart', 'active', '부품사', '[{"name": "위치센서", "category": "위치센서"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'http://www.nrtsensor.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '엔알티');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '6471.T', 'NSK Ltd.', '엔에스케이(일본정공)', 'TSE', 'JP', 'JPY', 'yfinance', 'active', '부품사', '[{"name": "볼스크류/리니어", "category": "볼스크류/리니어"}, {"name": "액추에이터", "category": "액추에이터"}, {"name": "감속기", "category": "감속기"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.nsk.com/' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '6471.T');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '688836.SS', 'Unitree Robotics (Yushu Technology Co., Ltd.)', '유니트리 로보틱스', 'SSE STAR', 'CN', 'CNY', 'yfinance', 'active', '부품사', '[{"name": "액추에이터", "category": "액추에이터"}, {"name": "모터", "category": "모터"}, {"name": "그리퍼핸드", "category": "그리퍼핸드"}]'::jsonb, ARRAY['humanoid','parts']::text[], NULL, NULL, NULL, 'https://www.unitree.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '688836.SS');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '9880.HK', 'UBTECH Robotics Corp Ltd', '유비테크 로보틱스', 'HKEX', 'CN', 'CNY', 'yfinance', 'active', NULL, '[{"name": "액추에이터", "category": "액추에이터"}, {"name": "그리퍼핸드", "category": "그리퍼핸드"}, {"name": "휴머노이드 로봇", "category": "기타"}]'::jsonb, ARRAY['humanoid']::text[], NULL, NULL, NULL, 'https://www.ubtrobot.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '9880.HK');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'Ewellix AB', '이웰릭스', NULL, 'SE', 'SEK', 'web_search', 'active', '부품사', '[{"name": "볼스크류/리니어", "category": "볼스크류/리니어"}, {"name": "액추에이터", "category": "액추에이터"}]'::jsonb, ARRAY['parts']::text[], 594000000, NULL, '2022-07-25', 'https://www.ewellix.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '이웰릭스');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '002472.SZ', 'Zhejiang Shuanghuan Driveline Co., Ltd.', '저장 솽환촨둥(쌍환전동)', 'SZSE', 'CN', 'CNY', 'yfinance', 'active', '부품사', '[{"name": "감속기", "category": "감속기"}, {"name": "볼스크류/리니어", "category": "볼스크류/리니어"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.gearsnet.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '002472.SZ');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '002050.SZ', 'Zhejiang Sanhua Intelligent Controls Co., Ltd.', '저장 싼화즈콩(삼화지능제어)', 'SZSE', 'CN', 'CNY', 'yfinance', 'active', '부품사', '[{"name": "액추에이터", "category": "액추에이터"}, {"name": "볼스크류/리니어", "category": "볼스크류/리니어"}, {"name": "기타", "category": "기타"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.sanhuagroup.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '002050.SZ');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'AgiBot (Zhiyuan Robotics)', '즈위안로보틱스(애지봇)', NULL, 'CN', 'CNY', 'web_search', 'active', '부품사', '[{"name": "액추에이터", "category": "액추에이터"}, {"name": "그리퍼핸드", "category": "그리퍼핸드"}, {"name": "휴머노이드 로봇", "category": "기타"}]'::jsonb, ARRAY['humanoid','parts']::text[], 2100000000, NULL, '2026-05-31', 'https://www.agibot.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '즈위안로보틱스(애지봇)');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'Tesollo Inc.', '테솔로', NULL, 'KR', 'KRW', 'dart', 'active', '부품사', '[{"name": "그리퍼핸드", "category": "그리퍼핸드"}, {"name": "액추에이터", "category": "액추에이터"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.tesollo.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '테솔로');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT 'TSLA', 'Tesla, Inc.', '테슬라', 'NASDAQ', 'US', 'USD', 'yfinance', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}, {"name": "액추에이터", "category": "액추에이터"}, {"name": "제어AI칩", "category": "제어AI칩"}]'::jsonb, ARRAY['humanoid']::text[], NULL, NULL, NULL, 'https://www.tesla.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = 'TSLA');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '6481.T', 'THK Co., Ltd.', '티에이치케이', 'TSE', 'JP', 'JPY', 'yfinance', 'active', '부품사', '[{"name": "볼스크류/리니어", "category": "볼스크류/리니어"}, {"name": "액추에이터", "category": "액추에이터"}]'::jsonb, ARRAY['humanoid','parts']::text[], NULL, NULL, NULL, 'https://www.thk.com/' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '6481.T');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '048770', 'TPC Robotics Corporation', '티피씨로보틱스', 'KOSDAQ', 'KR', 'KRW', 'fnguide', 'active', '부품사', '[{"name": "액추에이터", "category": "액추에이터"}, {"name": "기타", "category": "기타"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.tpcrobotics.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '048770');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'Figure AI, Inc.', '피규어 AI', NULL, 'US', 'USD', 'web_search', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}]'::jsonb, ARRAY['humanoid']::text[], 39000000000, 1900000000, '2025-09-16', 'https://www.figure.ai' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '피규어 AI');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '6324.T', 'Harmonic Drive Systems Inc.', '하모닉드라이브시스템즈', 'TSE', 'JP', 'JPY', 'yfinance', 'active', '부품사', '[{"name": "감속기", "category": "감속기"}, {"name": "액추에이터", "category": "액추에이터"}, {"name": "모터", "category": "모터"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.hds.co.jp/english/' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '6324.T');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '2049.TW', 'HIWIN Technologies Corp.', '하이윈', 'TWSE', 'TW', 'TWD', 'yfinance', 'active', '부품사', '[{"name": "볼스크류/리니어", "category": "볼스크류/리니어"}, {"name": "감속기", "category": "감속기"}, {"name": "모터", "category": "모터"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://www.hiwin.tw' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '2049.TW');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT '160190', 'HIGEN RNM Co., Ltd.', '하이젠알앤엠', 'KOSDAQ', 'KR', 'KRW', 'fnguide', 'active', '부품사', '[{"name": "모터", "category": "모터"}, {"name": "액추에이터", "category": "액추에이터"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://higenrnm.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = '160190');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'Hanwha Robotics Co., Ltd.', '한화로보틱스', NULL, 'KR', 'KRW', 'dart', 'active', '부품사', '[{"name": "기타", "category": "기타"}]'::jsonb, ARRAY['parts']::text[], NULL, NULL, NULL, 'https://hanwharobotics.co.kr' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '한화로보틱스');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT 'HEXA-B.ST', 'Hexagon AB (publ)', '헥사곤', 'STO', 'SE', 'EUR', 'yfinance', 'active', '부품사', '[{"name": "휴머노이드 로봇", "category": "기타"}, {"name": "위치센서", "category": "위치센서"}]'::jsonb, ARRAY['humanoid','parts']::text[], NULL, NULL, NULL, 'https://hexagon.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.ticker = 'HEXA-B.ST');
INSERT INTO companies (ticker, name, name_kr, market, country, currency, data_source, status, company_type, products, robot_roles, valuation_usd, funding_total_usd, valuation_asof, homepage_url) SELECT NULL, 'Holiday Robotics', '홀리데이로보틱스', NULL, 'KR', 'KRW', 'dart', 'active', NULL, '[{"name": "휴머노이드 로봇", "category": "기타"}]'::jsonb, ARRAY['humanoid']::text[], 689000000, 124459000, '2026-07-13', 'https://holiday-robotics.com' WHERE NOT EXISTS (SELECT 1 FROM companies x WHERE x.name_kr = '홀리데이로보틱스');
